### ISSUE TITLE
make onnamechanged more generic

### ISSUE THREAD

**Issue by ignatandrei** [raffaeler/SpeedyGenerators#1] opened 2021-11-05 03:45 UTC
Use Case
partial class Person: INotifyPropertyChanged{
[MakeProperty("LastName", compareValues:true)]
private string _lastName;

[MakeProperty("FirstName", compareValues:true)]
private string _firstName;

public string FullName
{
    get
    {
        return FirstName + " " + LastName;
    }
}
}

Requirement:
I want to change to 

OnPropertyChanged(nameof(this.FullName));

every time that FirstName and LastName changes

It will be helpfull that , instead of implement OnFirstNameChanged and OnLastNameChanged, I do have 

OnPropertyChanged(string propertyName, string oldValue, string newValue)

to handle both

**Comment by raffaeler** [comment] 2021-11-05 07:49
Hi, if I understand well, when you specify the "extra notify" flag to true, you want the generator to create a single partial method for all the properties in that class.

With the current code the solution is:
```C#
 [MakeProperty("FirstName", true)]
 private string? _firstName;

 [MakeProperty("LastName", true)]
 private string? _lastName;

 partial void OnFirstNameChanged(string? oldValue, string? newValue)
     => OnFullNameChanged(nameof(FirstName), oldValue, newValue);
 partial void OnLastNameChanged(string? oldValue, string? newValue)
     => OnFullNameChanged(nameof(LastName), oldValue, newValue);

 void OnFullNameChanged(string propertyName, string? oldValue, string? newValue) { }
``` 

If this is the request, I see a problem when there are many properties because you would require a large switch/case to distinguish the property name inside the partial method body. Not very practical.

Otherwise, aggregating the notification for just some of the properties would not be easy as well because it would require an additional parameter or a different attribute with a sort of "shared key".
It is a problem of complexity/usability. Is a shared key property worth it?

**Comment by ignatandrei** [comment] 2021-11-05 08:24
You can put both and the compiler will erase the non usefull one

For example, you can generate
``` csharp
set {
//code
OnFirstNameChanged();
OnPropertyChanged();
}
```

The implementation will be of the programmer - if he wants, 
he can implement OnFirstNameChanged 
or
he can implement OnPropertyChanged
Or 
none 
( and the compiler will erase the non-usefull one)

So  you give more options to the programmer

**Comment by raffaeler** [comment] 2021-11-05 13:25
One "global" notification per class is much better :)

With regards to the name, the candidate signature is:
```C#
partial void OnOnePropertyHasChanged(string? oldValue, string? newValue,
    [CallerMemberName] string? propertyName = null);
```

* I have to avoid "PropertyChanged" string inside the method name because this string is searched when you derive a class that implements the event (see readme in the doc for details)
* I prefer to avoid the prefix "OnPro..." at the beginning so that the intellisense provides a single suggestion when you want to manually trigger the `OnPropertyChanged` method (and thus, the event).
* The propertyName parameter must be the last one as it needs to be null (CallerMemberName requirement)

Sounds good?

**Comment by ignatandrei** [comment] 2021-11-05 15:32
Perfect. Let me know when you deploy on nuget

**Comment by raffaeler** [comment] 2021-11-05 19:50
@ignatandrei The signature I wrote this morning is faulty because of the property types.
It also doesn't make any sense to box the value types, therefore I would rather remove the old/new values entirely:
```
partial void OnOnePropertyHasChanged([CallerMemberName] string? propertyName = null);
```
One more point. I will add the call to this partial method only in the setters whose property has `ExtraNotify` to true.

**Comment by raffaeler** [comment] 2021-11-05 20:39
Version 1.0.15 contains the changed mentioned in this issue.
You can download the package from the home page of this repository and install as specified there using the dotnet CLI.
After some further tests I will publish this new release which will trigger the publishing in the official Nuget.org registry.

Please confirm from your side that it works as expected.
Thank you.

**Comment by ignatandrei** [comment] 2021-11-06 03:16
I will verify ASAP

**Comment by ignatandrei** [comment] 2021-11-06 04:18
Are you sure you have deployed 1.0.15 to NuGet ? I cannot find at  https://www.nuget.org/packages/SpeedyGenerators/
![image](https://user-images.githubusercontent.com/153982/140597605-97057a79-7eec-4378-a3d7-00dd529c7715.png)

**Comment by raffaeler** [comment] 2021-11-06 09:08
@ignatandrei I said:
> You can download the package from the home page of this repository and install as specified there using the dotnet CLI.

You find the package on the right side of the this **repository** home.

**Comment by ignatandrei** [comment] 2021-11-06 09:18
Sorry. I will do ASAP

**Comment by ignatandrei** [comment] 2021-11-06 12:39
It works. When you can / want, please push to nuget . Thanks

**Comment by raffaeler** [comment] 2021-11-06 14:03
I am making further tests and it still does not work appropriately in case of class hierarchies.
I can't publish this yet. It works in simple cases but not in complex ones.

**Comment by raffaeler** [comment] 2021-11-18 09:03
I wanted to give you an update. I did not have much time to spend on this, but I already wrote a portion of the needed code.

The problem is the following.
The partial method you suggested is meant to signal the changes to any property. But when you have a hierarchy (which is very common in viewmodels) you cannot access a partial method from a derived class. Every partial method is accessible only from the owning class.
This works well for the partial methods that are specific of a property, but not for the "global" one you suggested.

The alternatives are:
- generating a virtual (non-partial) method in the class which is lower in the hierarchy so that you can override it. Only the properties marked as ExtraNotify would call it.
- generating one global partial method for every class of the hierarchy so that every property calls its own global partial method. I don't like this solution because you will not reach the goal of having a single handler for all the properties.
- adding a custom event

**Comment by raffaeler** [comment] 2023-05-26 10:15
Given the new global method would not straightforward to use, I prefer to close this issue without adding it.

**Closed as completed by raffaeler** 2023-05-26 10:15 UTC
Labels: enhancement
